### ISSUE TITLE
Highlight matching paren on mouse-over

### ISSUE THREAD

**Issue by priyadarshan** [orthecreedence/highlight-lisp#6]
It would be very nice to have the option to highlight matching paren on mouse-over, like pastes at paste.lisp.org. See as example the same code of the `highlight-lisp` demo here: http://paste.lisp.org/display/143836

Thank you for `highlight-lisp`!

**Comment by priyadarshan** [comment]
`highlight-lisp` will hopefully be used for cl-cookbook (LispCookbook/cl-cookbook#43).

Being able to highlight matching paren on mouse-over would help studying the recipes (at least to absolute beginners like myself).

**Comment by pnathan** [comment]
:+1:

**Comment by orthecreedence** [comment]
OK FINE YOU WIN!!

Added paren matching in 93216f5. Works slightly differently than paste.lisp.org (their version is more robust, this one just highlights immediate matches). Pull down master and give it a shot (check out the [readme for details](https://github.com/orthecreedence/highlight-lisp#paren-matching))

**Comment by priyadarshan** [comment]
Thank you so much for the new feature!

**Comment by priyadarshan** [comment]
If I may, just as a reference, let me add a link to what looks related to the source for paste.lisp.org:
https://github.com/stassats/lisp-bots

I got it from here: https://gitlab.common-lisp.net/groups/lisppaste

**Comment by orthecreedence** [comment]
Cool, glad it's working well!

**Comment by vindarel** [comment]
Hi all ! This seems wonderful indeed but… where is it ? It is not deployed on the website, there is no mention of it in the README and I can't find a related PR :( I'm looking forward from seeing the change.

(so this is an open issue IMO)

**Comment by vindarel** [comment]
@priyadarshan indeed now the CL cookbook uses it :) (https://github.com/LispCookbook/cl-cookbook/pull/64#issuecomment-309528062)

**Comment by priyadarshan** [comment]
@vindarel Very nice PR.

Thank you!
