### ISSUE TITLE
Putting this on a CDN

### ISSUE THREAD

**Issue by eudoxia0** [orthecreedence/highlight-lisp#7]
would be pretty useful, since more or less every Lisp-related site I build uses this, and I hate putting copies of libraries into source code.

[cdnjs](https://cdnjs.com/) lets users submit libraries, though I'm not sure what the process is.

**Comment by orthecreedence** [comment]
This is done, just waiting for the PR to come through: https://github.com/cdnjs/cdnjs/pull/4191

**Comment by eudoxia0** [comment]
:+1:

**Comment by joca-bt** [comment]
You can use https://cdn.rawgit.com/.

**Comment by priyadarshan** [comment]
https://cdn.rawgit.com/orthecreedence/highlight-lisp/master/highlight-lisp.js

**Comment by orthecreedence** [comment]
Thanks for this. I honestly had a hell of a time trying to get this project on cdnjs and kind of just gave up after a while.
