### ISSUE TITLE
You can change the className, but the CSS requires it to be lisp

### ISSUE THREAD

**Issue by eudoxia0** [orthecreedence/highlight-lisp#9]
You can pass `className` option to highlight-lisp so you can highlight blocks with classes other than `lisp`. However, all the themes have selectors like `code.lisp`.

**Comment by orthecreedence** [comment]
I believe this is fixed by e9bd2476b86f9afd3d0c66b5f153d19b0ff10cb7. The class "hl-highlighted" is now added to all highlighted code blocks, and all themes have been updated to use the new auto-class. Can you give this a shot when you get a chance?

**Comment by eudoxia0** [comment]
It works perfectly, thank you very much!
